#!/bin/bash


################################################
#                                              #
#        Por: Ronualdo JSA - PU4RON            #
#                                              #
#                Janauba/MG                    #
#                                              #
################################################

mount -o remount,rw /

# Check we are root
if [ "$(id -u)" != "0" ];then
	echo "Este script deve ser executado como root" 1>&2
	exit 1
fi

if [ -z "$1" ]
then
      relink=never
else
      relink=${1}
fi

case ${1} in


*off)

  mount -o remount,rw /
  (cd /var/log/pi-star/; sudo /usr/local/bin/RemoteCommand 6073 UnLink)
  mount -o remount,ro /

  exit 0
;;


*reset)

  mount -o remount,rw /
  sudo systemctl restart ysfgateway.service	
  mount -o remount,ro /
  echo "* Retornando as configuracoes definidas pelo usuario."

  exit 0
;;

*)
  
valor=$relink

  mount -o remount,rw /
  (cd /var/log/pi-star/; sudo /usr/local/bin/RemoteCommand 6073 UnLink)
  sleep 1
  (cd /var/log/pi-star/; sudo /usr/local/bin/RemoteCommand 6073 LinkFCS724${valor})
  mount -o remount,ro /

  exit 0
;;
esac

exit 0
