#!/bin/bash

################################################
#                                              #
#        Por: Ronualdo JSA - PU4RON            #
#                                              #
#                Janauba/MG                    #
#                                              #
################################################
#
if [ "$(id -u)" != "0" ];then
	echo "Este script deve ser executado como root" 1>&2
	exit 1
fi

dmc="/etc/dmr2ysf"
unlink="4000"
ONysf="1"

SUF=$(grep -m 1 'Suffix=' /etc/ysfgateway | awk -F "=" '/Suffix/ {print $2}')
INDC=$(grep -m 1 'Callsign=' /etc/mmdvmhost | awk -F "=" '/Callsign/ {print $2}')
IDuser=$(grep -m 1 'Id=' /etc/mmdvmhost | awk -F "=" '/Id/ {print $2}')
CMDid="/usr/local/bin/RemoteCommand"
VGw=$(grep -m 1 'Startup=' /etc/ysfgateway | awk -F "=" '/Startup/ {print $2}')
VHost=$(grep -m 1 ';'${VGw}'' /usr/local/etc/YSFHosts.txt | awk -F ";" '/'${VGw}'/ {print $1}')
VALid=$(grep -A1 'Link' /var/log/pi-star/RemoteCommand-*.log | tail -n 1 | awk -F "FCS" '{print $2}' | awk -F '" to port:' '{print $1}')
TGDefault="${VHost}"
ENd="LinkFCS"

if [ -z "$1" ]
then
      tglink="${TGDefault}"
else
      tglink=${1}
fi

case ${1} in

*)
sudo rm ${dmc}

sudo touch ${dmc}
sudo chmod 777 ${dmc}

if [ $tglink == 4000 ]
then
      LTg="${TGDefault}"
else
      LTg="${tglink}"
fi

if [ $tglink == 1000 ]
then
      ONysf="0"
fi

if [ $tglink == 1001 ]
then
      ONysf="1"
      LTg="${TGDefault}"
fi

echo TG out:"${LTg}"
   
echo "[YSF Network]"                                 >> ${dmc}
echo "Callsign=${INDC}"                              >> ${dmc}
echo "Suffix=${SUF}"                                 >> ${dmc}
echo "GatewayAddress=127.0.0.1"                      >> ${dmc}
echo "GatewayPort=4200"                              >> ${dmc}
echo "LocalAddress=127.0.0.1"                        >> ${dmc}
echo "LocalPort=3200"                                >> ${dmc}
echo "Daemon=1"                                      >> ${dmc}
echo "FCSRooms=/usr/local/etc/FCSHosts.txt"          >> ${dmc}
echo "RadioID=${IDuser}"                             >> ${dmc}
echo "FICHCallsign=2"                                >> ${dmc}
echo "FICHCallMode=0"                                >> ${dmc}
echo "FICHFrameTotal=6"                              >> ${dmc}
echo "FICHMessageRoute=0"                            >> ${dmc}
echo "FICHVOIP=0"                                    >> ${dmc}
echo "FICHDataType=2"                                >> ${dmc}
echo "FICHSQLType=0"                                 >> ${dmc}
echo "FICHSQLCode=0"                                 >> ${dmc}
echo "DT1=1,34,97,95,43,3,17,0,0,0"                  >> ${dmc}
echo "DT2=0,0,0,0,108,32,28,32,3,8"                  >> ${dmc}
echo "Debug=0"                                       >> ${dmc}
echo ""                                              >> ${dmc}
echo "[DMR Network]"                                 >> ${dmc}
echo "Id=${IDuser}"                                  >> ${dmc}
echo "RptAddress=127.0.0.1"                          >> ${dmc}
echo "RptPort=62034"                                 >> ${dmc}
echo "LocalAddress=127.0.0.2"                        >> ${dmc}
echo "LocalPort=62033"                               >> ${dmc}
echo "Debug=0"                                       >> ${dmc}
echo "DefaultDstTG=${LTg}"                           >> ${dmc}
echo "TGUnlink=${unlink}"                            >> ${dmc}
echo "TGListFile=/usr/local/etc/TGList_YSF.txt"      >> ${dmc}
echo ""                                              >> ${dmc}
echo "[DMR Id Lookup]"                               >> ${dmc}
echo "File=/usr/local/etc/DMRIds.dat"                >> ${dmc}
echo "Time=24"                                       >> ${dmc}
echo ""                                              >> ${dmc}
echo "[Log]"                                         >> ${dmc}
echo "DisplayLevel=0"                                >> ${dmc}
echo "FileLevel=1"                                   >> ${dmc}
echo "FilePath=/var/log/pi-star"                     >> ${dmc}
echo "FileRoot=DMR2YSF"                              >> ${dmc}
echo ""                                              >> ${dmc}
echo "[Enabled]"                                     >> ${dmc}
echo "Enabled=${ONysf}"                              >> ${dmc}
sudo systemctl restart dmr2ysf.service               >/dev/null 2>&1 &
sudo systemctl restart ysfgateway.service            >/dev/null 2>&1 &
sleep 2
sudo  ${CMDid} 6073 ${ENd}${VALid}                   >/dev/null 2>&1 &
;;
esac
exit 0
