#!/bin/bash


################################################
#                                              #
#        Por: Ronualdo JSA - PU4RON            #
#                                              #
#                Janauba/MG                    #
#                                              #
################################################

mount -o remount,rw /

# Check we are root
if [ "$(id -u)" != "0" ];then
	echo "Este script deve ser executado como root" 1>&2
	exit 1
fi

if [ -z "$1" ]
then
      relink=never
else
      relink=${1}
fi

case ${1} in


*off)
  mount -o remount,rw /
  sudo systemctl restart ysfgateway.service >/dev/null 2>&1 &
  sleep 2
  sudo pistar-ysflink unlink >/dev/null 2>&1 &
  mount -o remount,ro /
  echo "* C4FM Desligado - Em espera."
  exit 0
;;


*reset)
  mount -o remount,rw /
  sudo systemctl restart ysfgateway.service >/dev/null 2>&1 &
  sleep 2	
  mount -o remount,ro /
  echo "* Retornando as configuracoes definidas pelo usuario."
  exit 0
;;

*)
  
valor=$relink
  mount -o remount,rw /
  sudo systemctl restart ysfgateway.service >/dev/null 2>&1 &
  sleep 3
  echo "* Link solicitado DG-ID:"$valor
  sudo pistar-ysflink fcs724${valor} >/dev/null 2>&1 &
  mount -o remount,ro /
  echo "* DG-ID:"$valor aceito.
  exit 0
;;
esac

exit 0
