#!/bin/bash

################################################
#                                              #
#        Por: Ronualdo JSA - PU4RON            #
#                                              #
#                Janauba/MG                    #
#                                              #
################################################
#
if [ "$(id -u)" != "0" ];then
	echo "Este script deve ser executado como root" 1>&2
	exit 1
fi

COM="/usr/local/bin/RemoteCommand 6073"
MODE="pistar-mmdvmhost-module Ysf"

if [ -z "$1" ]
then
      relink=never
else
      relink=${1}
fi

case ${1} in

*lig|Lig|LIG)
  (cd /var/log/pi-star/; sudo ${MODE} Enable) >/dev/null 2>&1 &
  echo "* -> Modalidade: YSF ${REST}"
  exit 0
;;

*desl|Desl|DESL)
  (cd /var/log/pi-star/; sudo ${MODE} Disable) >/dev/null 2>&1 &
  echo "* -> Modalidade: YSF ${REST}"
  exit 0
;;

*off|Off|OFF)
  sudo mount -o remount,rw / 2>&1
  sudo mount -o remount,rw /boot 2>&1

  ALVOFF="Startup="
  ALVOFY="DefaultDstTG="
  DIRC="/etc/ysfgateway"
  DIRY="/etc/dmr2ysf"

  sudo chmod 777 ${DIRC}
  sudo chmod 777 ${DIRY}

  sudo sed -i "s/Startup=.*/${ALVOFF}/"  ${DIRC}
  sudo sed -i "s/DefaultDstTG=.*/${ALVOFY}/"  ${DIRY}

  sudo systemctl restart ysfgateway.service  >/dev/null 2>&1 &
  sudo systemctl restart dmr2ysf.service >/dev/null 2>&1 &

  (cd /var/log/pi-star/; sudo ${COM} UnLink) >/dev/null 2>&1 &

  sudo mount -o remount,ro / 2>&1
  sudo mount -o remount,ro /boot 2>&1
  exit 0
;;


*reset)
  sudo systemctl restart ysfgateway.service  >/dev/null 2>&1 &	
  echo "* Retornando as configuracoes definidas pelo usuario."
  exit 0
;;

*)
  
VALOR=${relink}
  sudo mount -o remount,rw / 2>&1
  sudo mount -o remount,rw /boot 2>&1

  DIRC="/etc/ysfgateway"
  DIRYA="/etc/dmr2ysf"

  SERV=$(grep -m 1 ''${relink}';' /usr/local/etc/YSFHosts.txt | awk -F ";" '/'${relink}'/ {print $2}')
  SERVY=$(grep -m 1 ''${relink}';' /usr/local/etc/YSFHosts.txt | awk -F ";" '/'${relink}'/ {print $1}')

  sudo chmod 644 ${DIRC}
  sudo chmod 644 ${DIRYA}

  sudo sed -i "s/Startup=.*/Startup=${SERV}/"              ${DIRC}
  sudo sed -i "s/DefaultDstTG=.*/DefaultDstTG=${SERVY}/"   ${DIRYA}

  sudo systemctl restart dmr2ysf.service     >/dev/null 2>&1 & 
  sudo systemctl restart ysfgateway.service  >/dev/null 2>&1 &
  
  (cd /var/log/pi-star/; sudo ${COM} UnLink) >/dev/null 2>&1 &
  sleep 2
  (cd /var/log/pi-star/; sudo ${COM} LinkYSF${VALOR}) >/dev/null 2>&1 &

  echo "RJS: ${SERV} / ${VALOR}"
  
  sudo mount -o remount,ro / 2>&1
  sudo mount -o remount,ro /boot 2>&1
  
  exit 0
;;
esac

exit 0
