#!/bin/bash

################################################
#                                              #
#        Por: Ronualdo JSA - PU4RON            #
#                                              #
#                Janauba/MG                    #
#                                              #
################################################
#
if [ "$(id -u)" != "0" ];then
	echo "Este script deve ser executado como root" 1>&2
	exit 1
fi

COM="/usr/local/bin/RemoteCommand 6073"
MODE="pistar-mmdvmhost-module Ysf"

if [ -z "$1" ]
then
      relink=never
else
      relink=${1}
fi

case ${1} in

*lig|Lig|LIG)
  (cd /var/log/pi-star/; sudo ${MODE} Enable) >/dev/null 2>&1 &
  echo "* -> Modalidade: YSF ${REST}"
  exit 0
;;

*desl|Desl|DESL)
  (cd /var/log/pi-star/; sudo ${MODE} Disable) >/dev/null 2>&1 &
  echo "* -> Modalidade: YSF ${REST}"
  exit 0
;;

*off|Off|OFF)
  (cd /var/log/pi-star/; sudo ${COM} UnLink) >/dev/null 2>&1 &
  exit 0
;;


*reset)
  sudo systemctl restart ysfgateway.service  >/dev/null 2>&1 &	
  echo "* Retornando as configuracoes definidas pelo usuario."
  exit 0
;;

*)
  
VALOR=$relink
  (cd /var/log/pi-star/; sudo ${COM} UnLink) >/dev/null 2>&1 &
  sleep 1
  (cd /var/log/pi-star/; sudo ${COM} LinkYSF${VALOR}) >/dev/null 2>&1 &
  echo "Link YSF${VALOR}"
  exit 0
;;
esac

exit 0
