#!/bin/bash
#
################################################
#                                              #
#        Por: Ronualdo JSA - PU4RON            #
#                                              #
#                Janauba/MG                    #
#                                              #
################################################
#
MODE="pistar-mmdvmhost-module"
sudo mount -o remount,rw /

if [ -z "$1" ]; then
  script=$(nome "$0")
  exit 0
fi

if [ "$1" ]; then
  case ${1} in


([dD][mM][rR])
    alvo_a="Dmr"
    ;;
([dD][-][sS][tT][aA][rR])
    alvo_b="D-star"
    ;;
([yY][sS][fF])
    alvo_c="Ysf"
    ;;
([pP][2][5])
    alvo_d="P25"
    ;;
([nN][xX][dD][nN])
    alvo_e="Nxdn"
    ;;

*)
   echo "* ??? ${1}"
   exit 1
   ;;
 esac
 fi


if [ "$2" ]; then
  case ${2} in

  ([oO][nN])
    on_a="Enable"
    on_b="Enable"
    on_c="Enable"
    on_d="Enable"
    on_e="Enable"
    ;;

  ([oO][fF][fF])
    on_a="Disable"
    on_b="Disable"
    on_c="Disable"
    on_d="Disable"
    on_e="Disable"
    ;;

  *)
    echo "* ??? ${2}"
    exit 1
    ;;
  esac

else
  exit 1
fi

(cd /var/log/pi-star/; sudo ${MODE} ${alvo_a} ${on_a}) >/dev/null 2>&1 &
(cd /var/log/pi-star/; sudo ${MODE} ${alvo_b} ${on_b}) >/dev/null 2>&1 &
(cd /var/log/pi-star/; sudo ${MODE} ${alvo_c} ${on_c}) >/dev/null 2>&1 &
(cd /var/log/pi-star/; sudo ${MODE} ${alvo_d} ${on_d}) >/dev/null 2>&1 &
(cd /var/log/pi-star/; sudo ${MODE} ${alvo_e} ${on_e}) >/dev/null 2>&1 &

mount -o remount,ro /