#!/bin/bash

################################################
#                                              #
#        Por: Ronualdo JSA - PU4RON            #
#                                              #
#                Janauba/MG                    #
#                                              #
################################################

DIRgw="/etc/dmrgateway"

if [[ $(egrep -h -i "1234567|M1ABC" ${DIRgw} | wc -l) -gt 0 ]]; then
  exit 1;
fi

if [ `sed -n '/\[DMR Network\]/{n;p;}' /etc/mmdvmhost | cut -c 8` == 0 ]; then
	exit 1;
fi

if [ `sed -n '/\[DMR Network\]/{n;p;n;p;}' /etc/mmdvmhost | sed '1d' | awk -F = '{print $2}'` != 127.0.0.1 ]; then
	exit 1;
fi

mount -o remount,rw / 2>&1
mount -o remount,rw /boot 2>&1

if [ -z "$1" ]; then
      val=never
else
      val=${1}
fi

case ${1} in

*off|Off|OFF)
  sudo sed -i "s/\[DMR Network 1\]/\[DMR Network 1#\]/"  ${DIRgw}
  sudo sed -i "s/\[DMR Network 2\]/\[DMR Network 2#\]/"  ${DIRgw}
  sudo sed -i "s/\[DMR Network 3\]/\[DMR Network 3#\]/"  ${DIRgw}
  sudo sed -i "s/\[XLX Network\]/\[XLX Network#\]/"      ${DIRgw}
  sudo systemctl restart mmdvmhost.service > /dev/null 2>&1
  sudo systemctl restart dmrgateway.service > /dev/null 2>&1
  mount -o remount,ro / 2>&1
  mount -o remount,ro /boot 2>&1
  echo "* Network[1-2-3] desligados."
  exit 0
;;


*reset|Reset|RESET)
  sudo sed -i "s/\[DMR Network 1#\]/\[DMR Network 1\]/"  ${DIRgw}
  sudo sed -i "s/\[DMR Network 2#\]/\[DMR Network 2\]/"  ${DIRgw}
  sudo sed -i "s/\[DMR Network 3#\]/\[DMR Network 3\]/"  ${DIRgw}
  sudo sed -i "s/\[XLX Network#\]/\[XLX Network\]/"      ${DIRgw}
  sudo systemctl restart mmdvmhost.service > /dev/null 2>&1
  sudo systemctl restart dmrgateway.service > /dev/null 2>&1
  sudo systemctl restart ysfgateway.service > /dev/null 2>&1
  mount -o remount,ro / 2>&1
  mount -o remount,ro /boot 2>&1
  echo "* Network[1-2-3] ligados."
  echo "* Retornando configuracoes definidas pelo usuario."
  exit 0
;;

*)  
   echo ""
   exit 0;
;;
esac

exit 0
