#!/bin/bash
#
################################################
#                                              #
#        Por: Ronualdo JSA - PU4RON            #
#                                              #
#                Janauba/MG                    #
#                                              #
################################################
#
Ap="/etc/pistar-remote"
call=$(grep -m 1 'Callsign=' /etc/mmdvmhost | awk -F "=" '/Callsign/ {print $2}')



if [ -f "${Ap}" ]; then


   mount -o remount,rw /

   sudo cp -p ${Ap} ${Ap}.$(date +%Y%m%d)
   sudo rm ${Ap}

   sudo touch ${Ap}   
   sudo chmod 777 ${Ap}

   echo "[banner]"                                       >> ${Ap}
   echo "# Pi-Star config file"                          >> ${Ap}
   echo ""                                               >> ${Ap}
   echo "[enable]"                                       >> ${Ap}
   echo "enabled=true"                                   >> ${Ap}
   echo ""                                               >> ${Ap}
   echo "[keeper]"                                       >> ${Ap}
   echo "callsign=${call}"                               >> ${Ap}
   echo ""                                               >> ${Ap}
   echo "#[dmr]"                                         >> ${Ap}
   echo "#svckill=9999999"                               >> ${Ap}
   echo "#svcrestart=9999998"                            >> ${Ap}
   echo "#reboot=9999997"                                >> ${Ap}
   echo "#shutdown=9999996"                              >> ${Ap}
   echo "#hostfiles=9999995"                             >> ${Ap}
   echo ""                                               >> ${Ap}
   echo "[d-star]"                                       >> ${Ap}
   echo "# UR fields"                                    >> ${Ap}
   echo "#svckill=SVCKILL"                               >> ${Ap}
   echo "#svcrestart=SVCRSTRT"                           >> ${Ap}
   echo "#reboot=REBOOTPI"                               >> ${Ap}
   echo "#shutdown=SHUTDOWN"                             >> ${Ap}
   echo "#getip=GETIP"                                   >> ${Ap}
   echo "#hostfiles=HOSTFILE"                            >> ${Ap}
   echo "#8Ball=8BALL"                                   >> ${Ap}
   echo ""                                               >> ${Ap}
   echo "[ysf]"                                          >> ${Ap}
   echo "# ROOM commands"                                >> ${Ap}
   echo "#svckill=99999"                                 >> ${Ap}
   echo "#svcrestart=99998"                              >> ${Ap}
   echo "#reboot=99997"                                  >> ${Ap}
   echo "#shutdown=99996"                                >> ${Ap}
   echo "#hostfiles=99995"                               >> ${Ap}
   echo ""                                               >> ${Ap}
   echo "[p25]"                                          >> ${Ap}
   echo "# P25 Talkgroups are limited to 1->65535"       >> ${Ap}
   echo "#svckill=65531"                                 >> ${Ap}
   echo "#svcrestart=65532"                              >> ${Ap}
   echo "#reboot=65533"                                  >> ${Ap}
   echo "#shutdown=65534"                                >> ${Ap}
   echo "#hostfiles=65530"                               >> ${Ap}
   echo ""                                               >> ${Ap}
   echo "[dmr]"                                          >> ${Ap}
   echo "dgidOFF=4444400"                                >> ${Ap}
   echo "dgidRST=5555500"                                >> ${Ap}
   echo "dgid01=8888801"                                 >> ${Ap}
   echo "dgid02=8888802"                                 >> ${Ap}
   echo "dgid03=8888803"                                 >> ${Ap}
   echo "dgid04=8888804"                                 >> ${Ap}
   echo "dgid05=8888805"                                 >> ${Ap}
   echo "dgid06=8888806"                                 >> ${Ap}
   echo "dgid07=8888807"                                 >> ${Ap}
   echo "dgid08=8888808"                                 >> ${Ap}
   echo "dgid09=8888809"                                 >> ${Ap}
   echo "dgid10=8888810"                                 >> ${Ap}
   echo "dgid11=8888811"                                 >> ${Ap}
   echo "dgid12=8888812"                                 >> ${Ap}
   echo "dgid13=8888813"                                 >> ${Ap}
   echo "dgid14=8888814"                                 >> ${Ap}
   echo "dgid15=8888815"                                 >> ${Ap}
   echo "dgid16=8888816"                                 >> ${Ap}
   echo "dgid17=8888817"                                 >> ${Ap}
   echo "dgid18=8888818"                                 >> ${Ap}
   echo "dgid19=8888819"                                 >> ${Ap}
   echo "dgid20=8888820"                                 >> ${Ap}
   echo "dgid21=8888821"                                 >> ${Ap}
   echo "dgid22=8888822"                                 >> ${Ap}
   echo "dgid23=8888823"                                 >> ${Ap}
   echo "dgid24=8888824"                                 >> ${Ap}
   echo "dgid25=8888825"                                 >> ${Ap}
   echo "dgid26=8888826"                                 >> ${Ap}
   echo "dgid27=8888827"                                 >> ${Ap}
   echo "dgid28=8888828"                                 >> ${Ap}
   echo "dgid29=8888829"                                 >> ${Ap}
   echo "dgid30=8888830"                                 >> ${Ap}
   echo "dgid31=8888831"                                 >> ${Ap}
   echo "dgid32=8888832"                                 >> ${Ap}
   echo "dgid33=8888833"                                 >> ${Ap}
   echo "dgid34=8888834"                                 >> ${Ap}
   echo "dgid35=8888835"                                 >> ${Ap}
   echo "dgid36=8888836"                                 >> ${Ap}
   echo "dgid37=8888837"                                 >> ${Ap}
   echo "dgid38=8888838"                                 >> ${Ap}
   echo "dgid39=8888839"                                 >> ${Ap}
   echo "dgid40=8888840"                                 >> ${Ap}
   echo "dgid41=8888841"                                 >> ${Ap}
   echo "dgid42=8888842"                                 >> ${Ap}
   echo "dgid43=8888843"                                 >> ${Ap}
   echo "dgid44=8888844"                                 >> ${Ap}
   echo "dgid45=8888845"                                 >> ${Ap}
   echo "dgid46=8888846"                                 >> ${Ap}
   echo "dgid47=8888847"                                 >> ${Ap}
   echo "dgid48=8888848"                                 >> ${Ap}
   echo "dgid49=8888849"                                 >> ${Ap}
   echo "dgid50=8888850"                                 >> ${Ap}
   echo "dgid51=8888851"                                 >> ${Ap}
   echo "dgid52=8888852"                                 >> ${Ap}
   echo "dgid53=8888853"                                 >> ${Ap}
   echo "dgid54=8888854"                                 >> ${Ap}
   echo "dgid55=8888855"                                 >> ${Ap}
   echo "dgid56=8888856"                                 >> ${Ap}
   echo "dgid57=8888857"                                 >> ${Ap}
   echo "dgid58=8888858"                                 >> ${Ap}
   echo "dgid59=8888859"                                 >> ${Ap}
   echo "dgid60=8888860"                                 >> ${Ap}
   echo "dgid61=8888861"                                 >> ${Ap}
   echo "dgid62=8888862"                                 >> ${Ap}
   echo "dgid63=8888863"                                 >> ${Ap}
   echo "dgid64=8888864"                                 >> ${Ap}
   echo "dgid65=8888865"                                 >> ${Ap}
   echo "dgid66=8888866"                                 >> ${Ap}
   echo "dgid67=8888867"                                 >> ${Ap}
   echo "dgid68=8888868"                                 >> ${Ap}
   echo "dgid69=8888869"                                 >> ${Ap}
   echo "dgid70=8888870"                                 >> ${Ap}
   echo "dgid71=8888871"                                 >> ${Ap}
   echo "dgid72=8888872"                                 >> ${Ap}
   echo "dgid73=8888873"                                 >> ${Ap}
   echo "dgid74=8888874"                                 >> ${Ap}
   echo "dgid75=8888875"                                 >> ${Ap}
   echo "dgid76=8888876"                                 >> ${Ap}
   echo "dgid77=8888877"                                 >> ${Ap}
   echo "dgid78=8888878"                                 >> ${Ap}
   echo "dgid79=8888879"                                 >> ${Ap}
   echo "dgid80=8888880"                                 >> ${Ap}
   echo "dgid81=8888881"                                 >> ${Ap}
   echo "dgid82=8888882"                                 >> ${Ap}
   echo "dgid83=8888883"                                 >> ${Ap}
   echo "dgid84=8888884"                                 >> ${Ap}
   echo "dgid85=8888885"                                 >> ${Ap}
   echo "dgid86=8888886"                                 >> ${Ap}
   echo "dgid87=8888887"                                 >> ${Ap}
   echo "dgid88=8888888"                                 >> ${Ap}
   echo "dgid89=8888889"                                 >> ${Ap}
   echo "dgid90=8888890"                                 >> ${Ap}
   echo "dgid91=8888891"                                 >> ${Ap}
   echo "dgid92=8888892"                                 >> ${Ap}
   echo "dgid93=8888893"                                 >> ${Ap}
   echo "dgid94=8888894"                                 >> ${Ap}
   echo "dgid95=8888895"                                 >> ${Ap}
   echo "dgid96=8888896"                                 >> ${Ap}
   echo "dgid97=8888897"                                 >> ${Ap}
   echo "dgid98=8888898"                                 >> ${Ap}
   echo "dgid99=8888899"                                 >> ${Ap}
   echo "svckill=9999999"                                >> ${Ap}
   echo "svcrestart=9999998"                             >> ${Ap}
   echo "reboot=9999997"                                 >> ${Ap}
   echo "#shutdown=9999996"                              >> ${Ap}
   echo "#hostfiles=9999995"                             >> ${Ap}
   echo "Brasil_Link=8072400"                            >> ${Ap}
   echo "Brazilnet=8077777"                              >> ${Ap}
   echo "C4FM_Brazil=8072401"                            >> ${Ap}
   echo "PU2LRZ=8090558"                                 >> ${Ap}
   echo "PU4ARR=8095973"                                 >> ${Ap}
   echo "YSF_BRASIL=8056691"                             >> ${Ap}
   echo "YSF_Minas=8001466"                              >> ${Ap}
   echo "BRAZIL_724=8072526"                             >> ${Ap}
   echo "dmrOFF=3333300"                                 >> ${Ap}
   echo "dmrON=3333101"                                  >> ${Ap}
   echo "dstarOFF=3333302"                               >> ${Ap}
   echo "dstarON=3333303"                                >> ${Ap}
   echo "ysfOFF=3333304"                                 >> ${Ap}
   echo "ysfON=3333305"                                  >> ${Ap}
   echo "nxdnOFF=3333306"                                >> ${Ap}
   echo "nxdnON=3333307"                                 >> ${Ap}
   echo "p25OFF=3333308"                                 >> ${Ap}
   echo "p25ON=3333309"                                  >> ${Ap}
   echo "net0RSTon=4444400"                              >> ${Ap}
   echo "net0RSToff=4444401"                             >> ${Ap}
   echo "xlxOFF=4444402"                                 >> ${Ap}
   echo "xlxON=4444403"                                  >> ${Ap}
   echo "net1OFF=4444404"                                >> ${Ap}
   echo "net1ON=4444405"                                 >> ${Ap}
   echo "net2OFF=4444406"                                >> ${Ap}
   echo "net2ON=4444407"                                 >> ${Ap}
   echo "net3OFF=4444408"                                >> ${Ap}
   echo "net3ON=4444409"                                 >> ${Ap}
   echo "net4OFF=4444410"                                >> ${Ap}
   echo "net4ON=4444411"                                 >> ${Ap}
   echo "net5OFF=4444412"                                >> ${Ap}
   echo "net5ON=4444413"                                 >> ${Ap}
   echo "net6OFF=4444414"                                >> ${Ap}
   echo "net6ON=4444415"                                 >> ${Ap}
   echo "dmr2ysfOFF=4444416"                             >> ${Ap}
   echo "dmr2ysfON=4444417"                              >> ${Ap}
   echo "dyOFF=4444418"                                  >> ${Ap}
   echo "dyON=4444419"                                   >> ${Ap}
   echo ""                                               >> ${Ap}

   sleep 1
   sudo chmod 644 ${Ap}
   sleep 1

fi
exit 0